- type: replace
  path: /instance_groups/-
  value:
    name:      broker
    instances: 1
    azs:       [z1]
    vm_type:   default
    stemcell:  default

    networks:
      - name: default

    jobs:
      - name: broker
        release: safe
        properties:
          username: vault
          password: ((vault-broker-password))
          guid: ((vault-broker-guid))

          service:
            name: vault
            description: Your Very Own Vault of Secrets
            tags: [vault, credentials, secure, key-value]

          backend:
            token: ((vault-token))
            skip_verify: true

# broker registration errand
- type: replace
  path: /instance_groups/-
  value:
    lifecycle: errand
    name:      register-broker
    instances: 1
    azs:       [z1]
    vm_type:   default
    stemcell:  default

    networks:
      - name: default

    jobs:
    - name: broker-registrar
      release: broker-registrar
      properties:
        servicebroker:
          name: vault
        cf:
          api_url: ((cf-api-url))
          username: ((cf-username))
          password: ((cf-password))
          skip_ssl_validation: ((cf-skip-ssl-validation))

- type: replace
  path: /instance_groups/-
  value:
    lifecycle: errand
    name:      unregister-broker
    instances: 1
    azs:       [z1]
    vm_type:   default
    stemcell:  default

    networks:
      - name: default

    jobs:
    - name: broker-deregistrar
      release: broker-registrar
      properties:
        servicebroker:
          name: vault
        cf:
          api_url: ((cf-api-url))
          username: ((cf-username))
          password: ((cf-password))
          skip_ssl_validation: ((cf-skip-ssl-validation))

- type: replace
  path: /releases/-
  value:
    name: broker-registrar
    version: 3.3.1
    url: https://github.com/cloudfoundry-community/broker-registrar-boshrelease/releases/download/v3.3.1/broker-registrar-3.3.1.tgz
    sha1: c95283460a4f962cee1cacabb7333774783a24e9

- type: replace
  path: /variables/-
  value:
    name: cf-api-url

- type: replace
  path: /variables/-
  value:
    name: cf-username

- type: replace
  path: /variables/-
  value:
    name: cf-password

- type: replace
  path: /variables/-
  value:
    name: cf-skip-ssl-validation

- type: replace
  path: /variables/-
  value:
    name: vault-token

- type: replace
  path: /variables/-
  value:
    name: vault-broker-guid

- type: replace
  path: /variables/-
  value:
    name: vault-broker-password
    type: password
