---
- type: replace
  path: /instance_groups/name=vault/jobs/name=vault/properties?/drain/token
  value: ((vault_step_down_token))

- type: replace
  path: /releases/-
  value:
    name: cron
    version: "1.3.0"
    url: "https://bosh.io/d/github.com/cloudfoundry-community/cron-boshrelease?v=1.3.0"
    sha1: "fc04ff78ff958487be8829bb93d9023f6a87b7e6"

- type: replace
  path: /instance_groups/name=vault/jobs/-
  value:
    name: cron
    release: cron
    properties:
      cron:
        variables:
          TOKEN: ((vault_step_down_token))
        entries:
        - minute:  '*/5'
          hour:    '*'
          day:     '*'
          month:   '*'
          wday:    '*'
          user:    'vcap'
          script:
            name: renew-token.sh
            contents: |
              #!/bin/bash

              /usr/bin/curl \
                 --header "X-Vault-Token: $TOKEN" \
                 --request POST \
                 https://127.0.0.1:8200/v1/auth/token/renew-self