#!/bin/bash
#
# ci/scripts/testflight
#
# Script for testing a BOSH release
#
# author:  James Hunt <james@niftylogic.com>

set -eu
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

header() {
  echo
  echo "###############################################"
  echo
  echo $*
  echo
}

######
######
######
header "Checking the Concourse Pipeline Environment"
envok=0
checkenv() {
  local name=$1
  local val=$2

  if [[ -z "$val" ]]; then
    echo >&2 "The $name variable must be set."
    envok=1
  fi
}
checkenv BOSH_ENVIRONMENT   "${BOSH_ENVIRONMENT:-}"
checkenv BOSH_CA_CERT       "${BOSH_CA_CERT:-}"
checkenv BOSH_CLIENT        "${BOSH_CLIENT:-}"
checkenv BOSH_CLIENT_SECRET "${BOSH_CLIENT_SECRET:-}"
checkenv BOSH_DEPLOYMENT    "${BOSH_DEPLOYMENT:-}"
checkenv MANIFEST_PATH      "${MANIFEST_PATH:-}"
checkenv AWS_BUCKET_NAME    "${AWS_BUCKET_NAME}"
checkenv AWS_HOST_NAME      "${AWS_HOST_NAME}"
checkenv AWS_ACCESS_KEY     "${AWS_ACCESS_KEY:-}"
checkenv AWS_SECRET_KEY     "${AWS_SECRET_KEY:-}"
checkenv REPO_ROOT          "${REPO_ROOT:-}"
if [[ $envok != 0 ]]; then
  echo >&2 "Is your Concourse Pipeline misconfigured?"
  exit 1
fi

cd $REPO_ROOT
if [[ ! -f ${MANIFEST_PATH} ]]; then
  echo "Deployment manifest ${MANIFEST_PATH} does not exist"
  exit 1
fi

######
######
######
header "Cleaning up any previous '${BOSH_DEPLOYMENT}' deployments..."
bosh -n delete-deployment --force || true

######
######
######
header "Creating candidate BOSH release..."
bosh -n reset-release # in case dev_releases/ is in repo accidentally
cat > config/private.yml <<YAML
---
blobstore:
  provider: s3
  options:
    host: ${AWS_HOST_NAME}
    access_key_id: ${AWS_ACCESS_KEY}
    secret_access_key: ${AWS_SECRET_KEY}
YAML
bosh create-release
bosh upload-release --rebase

######
######
######
header "Choosing cloud-config options"
vm_type=$(  bosh int <(bosh cloud-config) --path /vm_types/0/name)
disk_type=$(bosh int <(bosh cloud-config) --path /disk_types/0/name)
network=$(  bosh int <(bosh cloud-config) --path /networks/0/name)
if ! az=$(  bosh int <(bosh cloud-config) --path /networks/0/subnets/0/azs/0)
then
  az=$(     bosh int <(bosh cloud-config) --path /networks/0/subnets/0/az)
fi

release_name=$(bosh int config/final.yml --path /final_name)
release_version=$(spruce json dev_releases/*/index.yml | jq -r ".builds[].version" | sed -e "s%+.*%%")

######
######
######
header "Generating ops-file overrides"
(cat <<EOF
---
- type: replace
  path: /name
  value: ${BOSH_DEPLOYMENT}

- type: replace
  path: /releases/name=${release_name}
  value:
    name: ${release_name}
    version: ${release_version}.latest

- type: replace
  path: /update/max_in_flight
  value: 3

- type: replace
  path: /update/serial
  value: false
EOF

for ig in $(spruce json ${MANIFEST_PATH} | jq -r ".instance_groups[].name"); do
  cat <<EOF
- type: replace
  path: /instance_groups/name=${ig}/vm_type
  value: ${vm_type}

- type: replace
  path: /instance_groups/name=${ig}/networks
  value: [{name: ${network}}]
EOF
  if [ -n "$az" ]; then
    cat <<EOF
- type: replace
  path: /instance_groups/name=${ig}/azs?
  value: [${az}]
EOF
  fi
done

for ig in $(spruce json $MANIFEST_PATH | jq -r ".instance_groups[] | select(.persistent_disk_type).name"); do
  cat <<EOF
- type: replace
  path: /instance_groups/name=${ig}/persistent_disk_type
  value: ${disk_type}

EOF
done) > overrides.yml

######
######
######
header "Deploying to ${BOSH_ENVIRONMENT}..."
bosh -n deploy $MANIFEST_PATH -o overrides.yml

header "Running tests"
set -x
safe target https://$(bosh instances --json| jq -r '.Tables[].Rows[0].ips') test -k
init=$(safe init --json)
token=$(jq -r '.root_token' <<< "$init")
keys=$(jq -r '.seal_keys[]' <<< "$init")
value="testvalue"
safe set secret/test value=$value
[ "$(safe get secret/test:value)" == "$value" ]

set +x
header "Testing BBR backup"
set -x
wget https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/download/v1.5.2/bbr-1.5.2-linux-amd64 -O bbr
chmod +x bbr
mkdir backup
./bbr deployment backup --artifact-path backup
bosh -n delete-deployment --force

set +x
header "Testing BBR restore"
set -x

bosh -n deploy $MANIFEST_PATH -o overrides.yml
./bbr deployment restore --artifact-path backup/*

set +x
header "Unsealing restored safe"
set -x

(
export VAULT_SKIP_VERIFY=1
for server in $(bosh instances --json| jq -r '.Tables[].Rows[].ips'); do
  export VAULT_ADDR="https://$server"
  for key in $keys; do
    vault operator unseal "$key"
  done
done
)
sleep 60

safe target https://$(bosh instances --json| jq -r '.Tables[].Rows[0].ips') test -k
safe auth token <<< "$token"
[ "$(safe get secret/test:value)" == "$value" ]
set +x
######
######
######
header "Cleaning up testflight '${BOSH_DEPLOYMENT}' deployment..."
bosh -n delete-deployment --force

echo
echo
echo
echo "SUCCESS"
exit 0
