name: safe

instance_groups:
  - name:      consul
    instances: 3
    azs:       [z1]
    vm_type:   default
    stemcell:  default

    persistent_disk_type: default

    networks:
      - name: default

    jobs:
      - name: consul-server
        release: safe
        provides:
          consul-server:
            shared: true
        properties:
          tls:
            ca: ((consul_ca.certificate))
            key: ((consul_ca.private_key))

  - name:      vault
    instances: 2
    azs:       [z1]
    vm_type:   default
    stemcell:  default

    # vault requires a persistent disk, otherwise
    # you will lose all of your stored secrets.
    persistent_disk_type: default

    networks:
      - name: default

    jobs:
      - name: consul-client
        release: safe
        properties:
          tls:
            certificate: ((client_cert.certificate))
            key: ((client_cert.private_key))
      - name: vault
        release: safe
        properties:
          tls:
            internal:
              certificate: ((vault_cert.certificate))
              key: ((vault_cert.private_key))

variables:
- name: consul_ca
  type: certificate
  options:
    common_name: ca
    is_ca: true
    duration: 3650
- name: client_cert
  type: certificate
  options:
    common_name: client.safe.consul
    alternative_names:
    - client.safe.consul
    - localhost
    - 127.0.0.1
    ca: consul_ca
- name: vault_cert
  type: certificate
  options: 
    common_name: vault.service.consul
    alternative_names:
      - active.vault.service.consul
      - standby.vault.service.consul
      - vault.service.consul
      - 127.0.0.1
    ca: consul_ca

update:
  canaries:          0
  max_in_flight:     1
  serial:            true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
- alias:   default
  os:      ubuntu-xenial
  version: latest

releases:
- name:    safe
  version: 1.2.1
  url:     https://github.com/emerald-squad/safe-boshrelease/releases/download/v1.2.1/safe-1.2.1.tgz
  sha1:    2ec4816a43e628cb846c3df902b908ffa8c3b101
