name: safe

instance_groups:
  - name:      vault
    instances: 3
    azs:       [z1]
    vm_type:   default
    stemcell:  default

    # vault requires a persistent disk, otherwise
    # you will lose all of your stored secrets.
    persistent_disk_type: default

    networks:
      - name: default

    jobs:
      - name: vault
        release: safe
        properties:
          safe:
            peer:
              tls:
                verify: false


update:
  canaries:          0
  max_in_flight:     1
  serial:            true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
- alias:   default
  os:      ubuntu-trusty
  version: latest

releases:
- name: safe
  version: 0.2.0
  url: https://github.com/cloudfoundry-community/safe-boshrelease/releases/download/v0.2.0/safe-0.2.0.tgz
  sha1: 417956a970faa348aebc7afd4d1f029395bb3719
