---
meta:
  name:    safe
  release: Safe (Vault) BOSH Release
  target:  pipes
  url:     https://pipes.starkandwayne.com

  initial_version: 0.0.1

  git:
    name:  Stark & Wayne CI Bot
    email: ci@starkandwayne.com

  bosh-lite:
    target:   ((bosh-url))
    username: ((bosh-client))
    password: ((bosh-password))
    cacert:   ((bosh-cacert))

  aws:
    endpoint:   ((s3-endpoint))
    access_key: ((s3-access-key))
    secret_key: ((s3-secret-key))

  github:
    owner:        emerald-squad
    repo:         safe-boshrelease
    branch:       master
    private_key:  ((github-key))
    access_token: ((github-access-token))

groups:
  - name: blobs
    jobs:
      - strongbox
      - vault-broker

jobs:
  - name: strongbox # {{{
    public: true
    plan:
    - in_parallel:
      - { get: git }
      - { get: strongbox, trigger: true }
    - task: update-strongbox
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: (( grab meta.image.name ))
            tag:        (( grab meta.image.tag ))
        inputs:
        - name: git
        - name: strongbox
        outputs:
        - name: pushme
        run:
          path: ./git/ci/scripts/update-blob
        params:
          REPO_ROOT:        git
          REPO_OUT:         pushme
          BLOB_DIR:         strongbox
          BLOB_NAME:        strongbox
          BLOB_BINARY:      strongbox-linux-amd64
          BLOB_CLEANUP:     strongbox/strongbox
          BLOB_DESTINATION: strongbox/strongbox
          AWS_HOST_NAME:    (( grab meta.aws.endpoint  ))
          AWS_ACCESS_KEY:   (( grab meta.aws.access_key ))
          AWS_SECRET_KEY:   (( grab meta.aws.secret_key ))
          BRANCH:           (( grab meta.github.branch ))
    - put: git
      params:
        rebase: true
        repository: pushme/git
  # }}}
  - name: vault-broker # {{{
    public: true
    plan:
    - in_parallel:
      - { get: git }
      - { get: vault-broker, trigger: true }
    - task: update-vault-broker
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: (( grab meta.image.name ))
            tag:        (( grab meta.image.tag ))
        inputs:
        - name: git
        - name: vault-broker
        outputs:
        - name: pushme
        run:
          path: ./git/ci/scripts/update-blob
        params:
          REPO_ROOT:        git
          REPO_OUT:         pushme
          BLOB_DIR:         vault-broker
          BLOB_NAME:        vault-broker
          BLOB_BINARY:      vault-broker-linux-amd64
          BLOB_CLEANUP:     vault-broker/vault-broker
          BLOB_DESTINATION: vault-broker/vault-broker
          AWS_HOST_NAME:    (( grab meta.aws.endpoint  ))
          AWS_ACCESS_KEY:   (( grab meta.aws.access_key ))
          AWS_SECRET_KEY:   (( grab meta.aws.secret_key ))
          BRANCH:           (( grab meta.github.branch ))
    - put: git
      params:
        rebase: true
        repository: pushme/git
  # }}}

resources:
  - name: strongbox # {{{
    type: github-release
    source:
      user:         jhunt
      repository:   go-strongbox
      access_token: (( grab meta.github.access_token ))
  # }}}
  - name: vault-broker # {{{
    type: github-release
    source:
      user:         cloudfoundry-community
      repository:   vault-broker
      access_token: (( grab meta.github.access_token ))
  # }}}
